name: .NET

on:
  workflow_dispatch:

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
        
    - name: Pack core nugets
      run: dotnet pack MarkusSecundus.YoowzxCalc -o ./nugets/core
    - name: Pack all nugets
      run: dotnet pack -o ./nugets/all
      
    - name: Zip core nugets
      uses: papeloto/action-zip@v1
      with:
        files: ./nugets/core
        dest: zips/core.zip
    - name: Zip all nugets
      uses: papeloto/action-zip@v1
      with:
        files: ./nugets/all
        dest: zips/all.zip
        
    - id: version_name
      uses: QwerMike/xpath-action@v1
      with:
        filename: 'Directory.Build.props'
        expression: '//Project/PropertyGroup/Version/text()'
        
    - name: Github Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v${{ steps.version_name.outputs.result }}"
        prerelease: false
        files: |
          zips/core.zip
          zips/all.zip
          
    - name: Publish to Nuget
      run: dotnet nuget push "./nugets/core/*.nupkg" -s "nuget.org" -k "${{ secrets.NUGET_TOKEN }}"
